[[section-architecture-constraints]]
== Architecture Constraints


[role="arc42help"]
****
.Contents
Any requirement that constrains software architects in their freedom of design and implementation decisions or decision about the development process. These constraints sometimes go beyond individual systems and are valid for whole organizations and companies.

.Motivation
Architects should know exactly where they are free in their design decisions and where they must adhere to constraints.
Constraints must always be dealt with; they may be negotiable, though.

.Form
Simple tables of constraints with explanations.
If needed you can subdivide them into
technical constraints, organizational and political constraints and
conventions (e.g. programming or versioning guidelines, documentation or naming conventions)
****

=== Technical Constraints
[width="100%",options="header"]
|====================
| Code | Constraint | Explanation 
| TC01 | Implementación con React |El frontend se desarrollará con React que es una librería de JavaScript para construir interfaces de usuario. Permite componer IUs complejas de pequeñas y aisladas piezas de código llamadas “componentes”. 
| TC02 | Uso de solid | La aplicación debe ser desarrollada siguiendo las especificaciones SOLID con un control descentralizado de los datos de los usuarios
| TC03 | No se puede usar un pod por defecto | Se tendrá que implementar un pod por cada usuario de la aplicación
| TC04 | Los usuarios podrán visualizar las rutas en un mapa | Se utilizará una alguna api de mapas para mostrar las rutas de los usuarios 
|====================
